spring:
  application:
    name: health-check-provider
eureka:
  instance:
    hostname: localhost
  client:
    instanceInfoReplicationIntervalSeconds: 10
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix: INFO