# service instance name
spring:
  application:
    # 服务名
    name: nacos-gateway
  cloud:
    nacos:
      discovery:
        # 服务注册中心
        server-addr: 127.0.0.1:8848
        file-extension: yaml
    sentinel:
      eager: true
      transport:
        dashboard: 127.0.0.1:8080
      # nacos配置持久化
#      datasource:
#        ds1:
#          nacos:
#            # nacos地址
#            server-addr: 127.0.0.1:8848
#            dataId: sentinel-gateway
#            groupId: DEFAULT_GROUP
#            data-type: json
#            rule-type: flow

    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://nacos-invoker
          predicates:
            - Path=/auth/**
            - Header=token, ^.{3}$
          filter:
            - order: 666
        - id: noAuth
          uri: lb://nacos-provider
          predicates:
            - Path=/title/**

server:
  # 服务端口
  port: 7000

management:
  # 端点检查（健康检查）
  endpoints:
    web:
      exposure:
        include: "*"