server:
  port: 8761
spring:
  application:
    name: ek-service
  profiles: slave1  
eureka:
  instance:
    hostname: slave1
  client:
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/
      
# 第二个---不可少
---
server:
  port: 8762
spring:
  application:
    name: ek-service
  profiles: slave2  
eureka:
  instance:
    hostname: slave2
  client:
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/